#!/usr/bin/env node
// Generates codex/AGENTS.md and codex/skills-manifest.json from the source-
// preserving snapshot created by sync.sh.
// Usage: node gen-index.mjs <codexDir> <provenanceTsv>
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const [, , codexDir, provenanceTsv] = process.argv;
if (!codexDir || !provenanceTsv) {
  console.error("Usage: node gen-index.mjs <codexDir> <provenanceTsv>");
  process.exit(1);
}

function frontmatter(markdown) {
  const match = markdown.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!match) return {};

  const lines = match[1].split(/\r?\n/);
  const values = {};
  for (let index = 0; index < lines.length; index += 1) {
    const field = lines[index].match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    if (!field) continue;
    const [, key, rawValue] = field;
    const value = rawValue.trim();
    if (key === "description" && /^[>|][+-]?$/.test(value)) {
      const block = [];
      for (index += 1; index < lines.length; index += 1) {
        if (/^\S/.test(lines[index])) {
          index -= 1;
          break;
        }
        block.push(lines[index].replace(/^\s{2}/, ""));
      }
      values[key] = value.startsWith(">")
        ? block.join("\n").replace(/(?<!\n)\n(?!\n)/g, " ").trim()
        : block.join("\n").trim();
      continue;
    }
    values[key] = value.replace(/^["']|["']$/g, "");
  }
  return values;
}

const skills = [];
for (const line of readFileSync(provenanceTsv, "utf8").trim().split("\n")) {
  if (!line) continue;
  const [path, source] = line.split("\t");
  const absolutePath = join(codexDir, path);
  if (!existsSync(absolutePath)) {
    throw new Error(`Provenance path does not exist: ${path}`);
  }
  const fm = frontmatter(readFileSync(absolutePath, "utf8"));
  skills.push({
    name: fm.name || path.split("/").at(-2),
    path,
    description: (fm.description || "").replace(/\s+/g, " ").trim(),
    source,
  });
}

skills.sort((left, right) => left.name.localeCompare(right.name) || left.path.localeCompare(right.path));

writeFileSync(
  join(codexDir, "skills-manifest.json"),
  JSON.stringify({ generatedBy: "codex/sync.sh", count: skills.length, skills }, null, 2) + "\n",
);

const truncate = (value, length) =>
  value.length > length ? `${value.slice(0, length - 1).trimEnd()}…` : value;
const rows = skills
  .map(
    (skill) =>
      `| [\`${skill.name}\`](${skill.path}) | ${truncate(skill.description || "—", 240)} | \`${skill.source}\` |`,
  )
  .join("\n");

const agents = `<!-- GENERATED by codex/sync.sh — do not edit by hand. Run \`npm run codex:sync\`. -->

# gravit-ai-toolkit — Codex skill bundle

This directory snapshots every marketplace skill hierarchy as plain files so
**Codex** (and any AGENTS.md-based tool) can use the skills without Claude Code's
plugin mechanism. Each source retains its \`skills/\` hierarchy under \`sources/\`;
only required shared assets and licenses are included alongside it.

**How to use in Codex:** read the matching \`SKILL.md\` linked below, then follow
its instructions. MCP-backed skills provide guidance text only unless the matching
MCP server is configured in the consuming environment.

${skills.length} indexed skills:

| Skill | When to use | Source |
|---|---|---|
${rows}
`;
writeFileSync(join(codexDir, "AGENTS.md"), agents);

console.log(`  wrote codex/AGENTS.md and codex/skills-manifest.json (${skills.length} skills)`);
