#!/usr/bin/env node
// Generates codex/AGENTS.md (the index Codex loads) and codex/skills-manifest.json
// by scanning every codex/skills/<name>/SKILL.md frontmatter.
//
// Usage: node gen-index.mjs <skillsDir> <codexDir> <provenanceTsv>
import { readFileSync, writeFileSync, readdirSync, existsSync, statSync } from "node:fs";
import { join } from "node:path";

const [, , skillsDir, codexDir, provenanceTsv] = process.argv;

// name -> "owner/repo@ref" provenance, from the TSV the sync script wrote.
const provenance = {};
if (provenanceTsv && existsSync(provenanceTsv)) {
  for (const line of readFileSync(provenanceTsv, "utf8").split("\n")) {
    const [name, origin] = line.split("\t");
    if (name) provenance[name] = origin;
  }
}

// Minimal YAML frontmatter reader — pulls scalar `name:` and `description:`.
function frontmatter(md) {
  const m = md.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!m) return {};
  const out = {};
  for (const line of m[1].split("\n")) {
    const kv = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    if (!kv) continue;
    let [, k, v] = kv;
    v = v.trim().replace(/^["']|["']$/g, "");
    if (v) out[k] = v;
  }
  return out;
}

const skills = [];
for (const entry of readdirSync(skillsDir).sort()) {
  const dir = join(skillsDir, entry);
  const skillMd = join(dir, "SKILL.md");
  if (!statSync(dir).isDirectory() || !existsSync(skillMd)) continue;
  const fm = frontmatter(readFileSync(skillMd, "utf8"));
  skills.push({
    name: fm.name || entry,
    dir: entry,
    description: (fm.description || "").replace(/\s+/g, " ").trim(),
    source: provenance[entry] || "unknown",
  });
}

// --- skills-manifest.json ---
writeFileSync(
  join(codexDir, "skills-manifest.json"),
  JSON.stringify(
    { generated: new Date().toISOString(), count: skills.length, skills },
    null,
    2,
  ) + "\n",
);

// --- AGENTS.md (the index Codex reads) ---
const truncate = (s, n) => (s.length > n ? s.slice(0, n - 1).trimEnd() + "…" : s);
const rows = skills
  .map(
    (s) =>
      `| [\`${s.name}\`](skills/${s.dir}/SKILL.md) | ${truncate(s.description || "—", 240)} | \`${s.source}\` |`,
  )
  .join("\n");

const agents = `<!-- GENERATED by codex/sync.sh — do not edit by hand. Run \`npm run codex:sync\`. -->

# gravit-ai-toolkit — Codex skill bundle

This directory ships every skill from the gravit-ai-toolkit marketplace as plain
files so **Codex** (and any AGENTS.md-based tool) can use them without Claude Code's
plugin mechanism. Each skill lives in \`skills/<name>/SKILL.md\`.

**How to use in Codex:** point at or read the relevant \`skills/<name>/SKILL.md\` for the
task at hand, then follow its instructions. Skills whose source is an MCP-backed plugin
(e.g. \`azure\`) provide the guidance text, but any MCP tool calls they reference only work
where that MCP server is configured.

${skills.length} skills:

| Skill | When to use | Source |
|---|---|---|
${rows}
`;
writeFileSync(join(codexDir, "AGENTS.md"), agents);

console.log(`  wrote codex/AGENTS.md and codex/skills-manifest.json (${skills.length} skills)`);
